### ISSUE TITLE
Denver - Jose Gallegos - Draft Brand Statement

### ISSUE THREAD

**Issue by josezilla** [ga-students/ga-dsiplus#2]
Passionate technical writer, communicator and programmer.  I transform technical jargon and jumbled documentation into simple language and easy explanations.  I use computation to solve mathematical problems, never forgetting that humans want the answers.

**Comment by CoachJoyhaugen** [comment]
Hi!  Do you mind re-posting this in the private repo here: 
https://git.generalassemb.ly/dsi-plus-2/draft-brand-statement/issues

Thanks so much!

**Comment by josezilla** [comment]
Hi Joy,

I followed the link you sent… Sorry for the mixup.
