### ISSUE TITLE
ATL-Maxime Bouadoumou-Draft Brand Statement

### ISSUE THREAD

**Issue by bkmaxime1** [ga-students/ga-dsiplus#3]
Aspiring data scientist willing, able and insatiable desire to learn new technologies applicable to the field . Great understanding of statistics and it applications in solving complex problems.

**Comment by CoachJoyhaugen** [comment]
Hi!  Do you mind re-posting this in the private repo here: 
https://git.generalassemb.ly/DSI-EAST-1/draft-brand-statement/tree/master

Thanks so much! 
Joy

**Comment by bkmaxime1** [comment]
I have done it

Thanks


________________________________
