### ISSUE TITLE
SF -Cheryl Andrew -Draft Brand Statement

### ISSUE THREAD

**Issue by andrewcheryl** [ga-students/ga-dsiplus#4]
Cheryl has a passion for solving problems and pushing the boundaries by taking on challenges that are considered insurmountable by others. She has a proven track record of delivering value for organizations by creating innovative and sustainable long-term solutions. Her understanding of business processes and her ability to build trusted and respected partnerships enable her to unlock the true potential in herself and the people she works with.

**Comment by CoachJoyhaugen** [comment]
Hi!  Do you mind re-posting this in the private repo here: 
https://git.generalassemb.ly/dsi-plus-2/draft-brand-statement/issues

Thanks so much! 
Joy

**Comment by andrewcheryl** [comment]
Done.  Sorry for error
Thanks
cheryl
