### ISSUE TITLE
Blake Cannon - DEN - Draft Brand Statement

### ISSUE THREAD

**Issue by wblakecannon** [ga-students/ga-dsiplus#5]
My objective is to conceptually unify statistics, data analysis, and their related method to understand and analyze actual phenomena with data.

**Comment by CoachJoyhaugen** [comment]
Hi!  Do you mind re-posting this in the private repo here: 
https://git.generalassemb.ly/dsi-plus-2/draft-brand-statement/issues

Thanks so much! 
Joy

**Comment by wblakecannon** [comment]
Okay. I already posted it but thought it disappeared because I got repos confused. It looks like it’s case #1 in the private repo.

BC
