### ISSUE TITLE
DEN - William Buck - Draft Brand Statement

### ISSUE THREAD

**Issue by williambuck** [ga-students/ga-dsiplus#6]
Problem solving is all about using data to understand. The path to understanding is not always clear, but experience and knowledge of the tools available will illuminate the path. My background in scientific pursuit and leadership training has taught me to start with a critical mind, continue with a curious fervor, and conclude with all options exhausted. I bring a focused and enthusiastic energy to every team and every problem, and love surrounding myself with people that will push me to learn more.

**Comment by CoachJoyhaugen** [comment]
Hi!  Do you mind re-posting this in the private repo here: 
https://git.generalassemb.ly/dsi-plus-2/draft-brand-statement/issues

Thanks so much! 
Joy

**Comment by williambuck** [comment]
Okay, I think its in the right place now
